type MetaPaidTouchGtmStorageTagConfig = {
  storageKey?: string;
  legacyLastTouchKey?: string;
  debugQueryKey?: string;
  ttlDays?: number;
};

const escapeForSingleQuotedJs = (value: string) => value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");

const positiveIntegerOrDefault = (value: number | undefined, fallback: number) =>
  Number.isInteger(value) && value !== undefined && value > 0 ? value : fallback;

export const renderMetaPaidTouchGtmStorageTag = (config: MetaPaidTouchGtmStorageTagConfig = {}) => {
  const storageKey = (config.storageKey ?? "biocom_paid_touch_before_checkout_v1").trim();
  const legacyLastTouchKey = (config.legacyLastTouchKey ?? "_p1s1a_last_touch").trim();
  const debugQueryKey = (config.debugQueryKey ?? "__seo_paid_touch_debug").trim();
  const ttlDays = positiveIntegerOrDefault(config.ttlDays, 7);

  if (!storageKey) throw new Error("storageKey is required");
  if (!legacyLastTouchKey) throw new Error("legacyLastTouchKey is required");
  if (!debugQueryKey) throw new Error("debugQueryKey is required");

  const lines = [
    "<script>",
    "(function () {",
    "  var CONFIG = {",
    `    storageKey: '${escapeForSingleQuotedJs(storageKey)}',`,
    `    legacyLastTouchKey: '${escapeForSingleQuotedJs(legacyLastTouchKey)}',`,
    `    debugQueryKey: '${escapeForSingleQuotedJs(debugQueryKey)}',`,
    `    ttlMs: ${ttlDays} * 24 * 60 * 60 * 1000`,
    "  };",
    "",
    "  function trim(value) {",
    "    return typeof value === 'string' ? value.trim() : '';",
    "  }",
    "",
    "  function firstNonEmpty(values) {",
    "    for (var i = 0; i < values.length; i += 1) {",
    "      var value = trim(values[i]);",
    "      if (value) return value;",
    "    }",
    "    return '';",
    "  }",
    "",
    "  function safeParse(raw) {",
    "    if (!raw) return {};",
    "    try {",
    "      var parsed = JSON.parse(raw);",
    "      return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};",
    "    } catch (error) {",
    "      return {};",
    "    }",
    "  }",
    "",
    "  function readJsonStorage(storage, key) {",
    "    try {",
    "      if (!storage) return {};",
    "      return safeParse(storage.getItem(key));",
    "    } catch (error) {",
    "      return {};",
    "    }",
    "  }",
    "",
    "  function writeJsonStorage(storage, key, value) {",
    "    try {",
    "      if (!storage) return;",
    "      storage.setItem(key, JSON.stringify(value));",
    "    } catch (error) {}",
    "  }",
    "",
    "  function safeUrl(urlLike) {",
    "    try {",
    "      return new URL(urlLike || location.href, location.origin);",
    "    } catch (error) {",
    "      return null;",
    "    }",
    "  }",
    "",
    "  function param(url, key) {",
    "    if (!url) return '';",
    "    return trim(url.searchParams.get(key));",
    "  }",
    "",
    "  function isPaymentPath(pathname) {",
    "    var path = trim(pathname).toLowerCase();",
    "    return path.indexOf('/shop_payment') >= 0 || path.indexOf('/shop_order_done') >= 0;",
    "  }",
    "",
    "  function isCommonAlias(value) {",
    "    var normalized = trim(value).toLowerCase();",
    "    return normalized === 'meta_biocom_광고별칭' || normalized.indexOf('광고별칭') >= 0;",
    "  }",
    "",
    "  function isMetaMacro(value) {",
    "    return /\\{\\{\\s*(campaign|adset|ad)\\.id\\s*\\}\\}/i.test(trim(value));",
    "  }",
    "",
    "  function numericId(value) {",
    "    var normalized = trim(value);",
    "    return /^\\d{8,}$/.test(normalized) ? normalized : '';",
    "  }",
    "",
    "  function hostFromUrl(urlLike) {",
    "    var url = safeUrl(urlLike);",
    "    return url ? trim(url.hostname).toLowerCase() : '';",
    "  }",
    "",
    "  function inferClickIdType(url) {",
    "    if (param(url, 'fbclid')) return 'fbclid';",
    "    if (param(url, 'gclid')) return 'gclid';",
    "    if (param(url, 'ttclid')) return 'ttclid';",
    "    if (param(url, 'fbc')) return 'fbc';",
    "    if (param(url, 'fbp')) return 'fbp';",
    "    return '';",
    "  }",
    "",
    "  function looksMeta(value) {",
    "    var text = trim(value).toLowerCase();",
    "    if (!text) return false;",
    "    return text.indexOf('utm_source=meta') >= 0 ||",
    "      text.indexOf('utm_source=facebook') >= 0 ||",
    "      text.indexOf('utm_source=instagram') >= 0 ||",
    "      text.indexOf('facebook.com') >= 0 ||",
    "      text.indexOf('instagram.com') >= 0 ||",
    "      /(^|[^a-z0-9])(meta|facebook|instagram|fb|ig)([^a-z0-9]|$)/.test(text);",
    "  }",
    "",
    "  function evidenceFromSnapshot(snapshot) {",
    "    var evidence = [];",
    "    if (snapshot.metaCampaignId) evidence.push('numeric_meta_campaign_id');",
    "    if (snapshot.metaAdsetId) evidence.push('numeric_meta_adset_id');",
    "    if (snapshot.metaAdId) evidence.push('numeric_meta_ad_id');",
    "    if (snapshot.campaignAlias) evidence.push(isCommonAlias(snapshot.campaignAlias) ? 'common_campaign_alias' : 'campaign_alias');",
    "    if (snapshot.campaignAlias && !isCommonAlias(snapshot.campaignAlias) && !isMetaMacro(snapshot.campaignAlias)) evidence.push('unique_campaign_alias');",
    "    if (looksMeta(snapshot.source)) evidence.push('utm_source_meta');",
    "    if (looksMeta(snapshot.medium)) evidence.push('utm_medium_meta');",
    "    if (looksMeta(snapshot.campaign)) evidence.push('utm_campaign_meta');",
    "    if (looksMeta(snapshot.landing)) evidence.push('landing_meta');",
    "    if (looksMeta(snapshot.referrer) || looksMeta(snapshot.referrerHost)) evidence.push('referrer_meta');",
    "    if (snapshot.clickIdType) evidence.push('click_id_present_' + snapshot.clickIdType);",
    "    if (snapshot.landingPath && !isPaymentPath(snapshot.landingPath)) evidence.push('landing_path_non_payment');",
    "    if (isMetaMacro(snapshot.campaign) || isMetaMacro(snapshot.term) || isMetaMacro(snapshot.content) || isMetaMacro(snapshot.landing)) evidence.push('meta_macro_placeholder');",
    "    return evidence;",
    "  }",
    "",
    "  function gradeSnapshot(snapshot, evidence) {",
    "    if (snapshot.metaCampaignId && (snapshot.metaAdsetId || snapshot.metaAdId)) return { grade: 'A', confidence: snapshot.metaAdsetId && snapshot.metaAdId ? 0.96 : 0.9 };",
    "    if (evidence.indexOf('unique_campaign_alias') >= 0) return { grade: 'B', confidence: 0.74 };",
    "    if (evidence.indexOf('meta_macro_placeholder') >= 0) return { grade: 'D', confidence: 0.2 };",
    "    var hasOnlyClick = snapshot.clickIdType && evidence.length <= 2 && evidence.indexOf('landing_path_non_payment') >= 0;",
    "    if (hasOnlyClick) return { grade: 'D', confidence: 0.35 };",
    "    if (evidence.indexOf('landing_path_non_payment') >= 0 && (evidence.indexOf('utm_source_meta') >= 0 || evidence.indexOf('utm_campaign_meta') >= 0 || evidence.indexOf('referrer_meta') >= 0 || evidence.indexOf('landing_meta') >= 0)) return { grade: 'C', confidence: 0.58 };",
    "    return { grade: 'D', confidence: 0.3 };",
    "  }",
    "",
    "  function isExpired(snapshot) {",
    "    var capturedAt = Date.parse(trim(snapshot.capturedAt));",
    "    return Number.isFinite(capturedAt) && Date.now() - capturedAt > CONFIG.ttlMs;",
    "  }",
    "",
    "  function shouldReplace(existing, incoming) {",
    "    if (!existing || typeof existing !== 'object' || isExpired(existing)) return true;",
    "    var rank = { A: 4, B: 3, C: 2, D: 1 };",
    "    var existingRank = rank[existing.grade] || 0;",
    "    var incomingRank = rank[incoming.grade] || 0;",
    "    if (incomingRank > existingRank) return true;",
    "    if (incomingRank < existingRank) return false;",
    "    return Number(incoming.confidence || 0) > Number(existing.confidence || 0);",
    "  }",
    "",
    "  function buildSnapshot() {",
    "    var url = safeUrl(location.href);",
    "    if (!url || isPaymentPath(url.pathname)) return null;",
    "    var referrer = trim(document.referrer || '');",
    "    var campaignAlias = firstNonEmpty([param(url, 'campaign_alias'), param(url, 'campaignAlias')]);",
    "    var source = param(url, 'utm_source');",
    "    var medium = param(url, 'utm_medium');",
    "    var campaign = param(url, 'utm_campaign');",
    "    var term = param(url, 'utm_term');",
    "    var content = param(url, 'utm_content');",
    "    var clickIdType = inferClickIdType(url);",
    "    var hasMetaContext = Boolean(",
    "      param(url, 'meta_campaign_id') ||",
    "      param(url, 'meta_adset_id') ||",
    "      param(url, 'meta_ad_id') ||",
    "      looksMeta(source) ||",
    "      looksMeta(medium) ||",
    "      looksMeta(campaign) ||",
    "      looksMeta(campaignAlias) ||",
    "      looksMeta(location.href) ||",
    "      looksMeta(referrer) ||",
    "      clickIdType === 'fbclid' || clickIdType === 'fbc' || clickIdType === 'fbp'",
    "    );",
    "    var snapshot = {",
    "      schemaVersion: '2026-05-26.paid-touch-before-checkout.v1',",
    "      capturedAt: new Date().toISOString(),",
    "      source: source,",
    "      medium: medium,",
    "      campaign: campaign,",
    "      term: term,",
    "      content: content,",
    "      metaCampaignId: numericId(param(url, 'meta_campaign_id')) || (hasMetaContext ? numericId(firstNonEmpty([param(url, 'utm_campaign'), param(url, 'utm_id')])) : ''),",
    "      metaAdsetId: numericId(param(url, 'meta_adset_id')) || (hasMetaContext ? numericId(param(url, 'utm_term')) : ''),",
    "      metaAdId: numericId(param(url, 'meta_ad_id')) || (hasMetaContext ? numericId(param(url, 'utm_content')) : ''),",
    "      campaignAlias: campaignAlias,",
    "      metaSiteSource: param(url, 'meta_site_source'),",
    "      metaPlacement: param(url, 'meta_placement'),",
    "      landing: location.href,",
    "      landingPath: url.pathname || '/',",
    "      referrer: referrer,",
    "      referrerHost: hostFromUrl(referrer),",
    "      clickIdType: clickIdType,",
    "      clickIdHash: ''",
    "    };",
    "    var evidence = evidenceFromSnapshot(snapshot);",
    "    if (!evidence.length) return null;",
    "    var grade = gradeSnapshot(snapshot, evidence);",
    "    snapshot.grade = grade.grade;",
    "    snapshot.confidence = grade.confidence;",
    "    snapshot.evidence = evidence;",
    "    return snapshot;",
    "  }",
    "",
    "  function toLegacyLastTouch(snapshot, previous) {",
    "    var merged = previous && typeof previous === 'object' ? previous : {};",
    "    return {",
    "      capturedAt: snapshot.capturedAt,",
    "      landing: snapshot.landing,",
    "      referrer: snapshot.referrer,",
    "      utm_source: firstNonEmpty([snapshot.source, trim(merged.utm_source)]),",
    "      utm_medium: firstNonEmpty([snapshot.medium, trim(merged.utm_medium)]),",
    "      utm_campaign: firstNonEmpty([snapshot.campaign, trim(merged.utm_campaign)]),",
    "      utm_term: firstNonEmpty([snapshot.term, trim(merged.utm_term)]),",
    "      utm_content: firstNonEmpty([snapshot.content, trim(merged.utm_content)]),",
    "      gclid: trim(merged.gclid),",
    "      fbclid: trim(merged.fbclid),",
    "      ttclid: trim(merged.ttclid),",
    "      paidTouchBeforeCheckout: snapshot",
    "    };",
    "  }",
    "",
    "  function debugLog() {",
    "    try {",
    "      if (new URLSearchParams(location.search).get(CONFIG.debugQueryKey) !== '1') return;",
    "      console.log.apply(console, ['[seo-paid-touch]'].concat([].slice.call(arguments)));",
    "    } catch (error) {}",
    "  }",
    "",
    "  var incoming = buildSnapshot();",
    "  if (!incoming) return;",
    "  var existing = readJsonStorage(window.localStorage, CONFIG.storageKey);",
    "  if (!shouldReplace(existing, incoming)) {",
    "    debugLog('keep existing paid touch', existing.grade, incoming.grade);",
    "    return;",
    "  }",
    "  writeJsonStorage(window.localStorage, CONFIG.storageKey, incoming);",
    "  writeJsonStorage(window.sessionStorage, CONFIG.storageKey, incoming);",
    "  writeJsonStorage(window.localStorage, CONFIG.legacyLastTouchKey, toLegacyLastTouch(incoming, readJsonStorage(window.localStorage, CONFIG.legacyLastTouchKey)));",
    "  debugLog('stored paid touch', incoming.grade, incoming.evidence);",
    "})();",
    "</script>",
  ];

  return lines.join("\n");
};
